/** Verify the no-proxy path: a key in the page, the browser calling Anthropic itself. */
const [, , url, port] = process.argv;
const list = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
const ws = new WebSocket(list.find((t) => t.type === 'page').webSocketDebuggerUrl);
let id = 0; const pending = new Map(); const posts = [];
const send = (m, p = {}) => new Promise((r) => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method: m, params: p })); });
ws.onmessage = (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m.result); pending.delete(m.id); return; }
  if (m.method === 'Network.requestWillBeSent' && m.params.request.url.includes('api.anthropic.com')) posts.push((m.params.request.postData ?? '').length); };
await new Promise((r) => (ws.onopen = r));
await send('Page.enable'); await send('Runtime.enable'); await send('Network.enable');
await send('Emulation.setDeviceMetricsOverride', { width: 1150, height: 1200, deviceScaleFactor: 1 });
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const ev = async (x) => (await send('Runtime.evaluate', { expression: x, returnByValue: true, awaitPromise: true })).result?.value;
await send('Page.navigate', { url }); await wait(7000);
const room = await ev(`new URL(location.href).searchParams.get('room')`);
const B = `https://firestore.googleapis.com/v1/projects/avi-math-study/databases/(default)/documents/rooms/${room}/strokes`;
const K = 'YOUR_FIREBASE_API_KEY';
const add = (d, p, n) => ev(`fetch(${JSON.stringify(`${B}?documentId=${d}&key=${K}`)},{method:'POST',headers:{'Content-Type':'application/json'},body:${JSON.stringify(JSON.stringify({fields:{t:{stringValue:'ink'},c:{stringValue:'ink'},w:{integerValue:'6'},p:{stringValue:p},n:{integerValue:String(n)}}}))}}).then(r=>r.status)`);
await add('a', '0.10,0.20,0.8;0.30,0.20,0.8', 1);
await add('b', '0.20,0.10,0.8;0.20,0.30,0.8', 2);
await wait(2500);
await ev(`localStorage.setItem('avi-math-ocr-key','sk-ant-dummy-for-plumbing')`);
await send('Page.reload'); await wait(7000);
await ev(`[...document.querySelectorAll('button')].find(b=>b.textContent.includes('נוסחה ב-LaTeX'))?.click()`);
await wait(9000);
console.log('status        :', JSON.stringify(await ev(`document.querySelector('.state')?.textContent?.trim()`)));
console.log('calls to api  :', posts.length, posts.map(n => `${Math.round(n/1024)}KB`).join(', '));
console.log('setup row gone:', !(await ev(`!!document.querySelector('.setup')`)));
for (const d of ['a','b']) await ev(`fetch(${JSON.stringify(`${B}/${d}?key=${K}`)},{method:'DELETE'}).then(r=>r.status)`);
ws.close();
